conf_name: 'RKR3_2_resnet18_VD'
dataset: 'VD'
batch_size: 200
epochs: 320

model:
  name: 'resnet-18'
  K: 2
  task_num: 10
  classes: [1000, 100, 100, 2, 47, 43, 1623, 10, 101, 102]
  RG: True
  SFG: True
  multi_head: True