conf_name: 'RKR3_2_resnet18_cifar100'
dataset: 'CIFAR100'
batch_size: 100
epochs: 320

model:
  name: 'resnet-18'
  K: 2
  task_num: 10
  classes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
  RG: True
  SFG: True
  multi_head: True